<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitd2d2af1ad5d1d2ae44df805fbf46b680
{
    public static $prefixLengthsPsr4 = array (
        'C' => 
        array (
            'CakeWP\\CF7Blocks\\' => 17,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'CakeWP\\CF7Blocks\\' => 
        array (
            0 => __DIR__ . '/../..' . '/app',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitd2d2af1ad5d1d2ae44df805fbf46b680::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitd2d2af1ad5d1d2ae44df805fbf46b680::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
