<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'CakeWP\\CF7Blocks\\Handlers\\' => array($baseDir . '/app/handlers'),
    'CakeWP\\CF7Blocks\\Core\\' => array($baseDir . '/app/core'),
    'CakeWP\\CF7Blocks\\' => array($baseDir . '/app'),
);
