<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit1f0da40120b254f897c60d28ead23ab4
{
    public static $prefixLengthsPsr4 = array (
        'C' => 
        array (
            'CakeWP\\CF7Blocks\\' => 17,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'CakeWP\\CF7Blocks\\' => 
        array (
            0 => __DIR__ . '/../..' . '/app',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit1f0da40120b254f897c60d28ead23ab4::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit1f0da40120b254f897c60d28ead23ab4::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit1f0da40120b254f897c60d28ead23ab4::$classMap;

        }, null, ClassLoader::class);
    }
}
