/**
 * WordPress Dependencies
 */
import { isEmpty } from 'lodash';
import { __ } from '@wordpress/i18n';
import { useEffect } from '@wordpress/element';
import { useBlockProps } from '@wordpress/block-editor';

/**
 * Custom Dependencies
 */
import Toolbar from './toolbar';
import Inspector from './inspector';
import classnames from 'classnames';
import PreviewMode from './components/preview-mode';
import EditMode from './components/edit-mode';
import generateFieldName from '../utils/generate-name';

export default function edit( props ) {
	const blockProps = useBlockProps( {
		className: classnames( {
			[ `cf7-block-${ props.attributes.type }` ]: true,
			'cf7-block-selection-field-editing': props.isSelected,
		} ),
	} );

	const {
		id,
		items,
		type,
		isRequired,
		name,
		isLabelFirst,
		autogeneratedName,
	} = props.attributes;

	useEffect( () => {
		// Generating a new field name, if needed.
		if (
			isEmpty( autogeneratedName ) ||
			! autogeneratedName.startsWith( type )
		) {
			const newAutogeneratedName = generateFieldName( type );
			props.setAttributes( { autogeneratedName: newAutogeneratedName } );
		}
	}, [ type ] );

	return (
		<>
			<div { ...blockProps }>
				{ ! props.isSelected ? (
					<PreviewMode
						id={ id }
						type={ type }
						name={ name }
						items={ items }
						autogeneratedName={ autogeneratedName }
						isRequired={ isRequired }
						isLabelFirst={ isLabelFirst }
					/>
				) : (
					<EditMode
						id={ id }
						items={ items }
						type={ type }
						name={ name }
						isRequired={ isRequired }
						isLabelFirst={ isLabelFirst }
						autogeneratedName={ autogeneratedName }
						onUpdate={ ( newItems ) =>
							props.setAttributes( { items: newItems } )
						}
					/>
				) }
			</div>
			<Toolbar { ...props } />
			<Inspector { ...props } />
		</>
	);
}
