/**
 * WordPress Dependencies
 */
import { __, sprintf } from '@wordpress/i18n';
import { PanelBody, TextControl, ToggleControl } from '@wordpress/components';
import {
	InspectorControls,
	InspectorAdvancedControls,
} from '@wordpress/block-editor';

/**
 * Custom Dependencies
 */

import { convertSelectionBlockToCF7Shortcode } from '../utils/convert-to-cf7-shortcode';

function Inspector( props ) {
	const {
		id,
		type,
		name,
		isLabelFirst,
		isRequired,
		autogeneratedName,
	} = props.attributes;

	return (
		<>
			<InspectorControls>
				<PanelBody title={ __( 'Generated Shortcode', 'cf7-blocks' ) }>
					<code>
						{ convertSelectionBlockToCF7Shortcode(
							props.attributes
						) }
					</code>
				</PanelBody>
				<PanelBody title={ __( 'General', 'cf7-blocks' ) }>
					<TextControl
						value={ name }
						label={ __( 'Name', 'cf7-blocks' ) }
						placeholder={ autogeneratedName }
						help={ __(
							'Assign a unique field name',
							'cf7-blocks'
						) }
						onChange={ ( newName ) => {
							const normalizedName = newName
								.toLowerCase()
								.replace( ' ', '-' );

							props.setAttributes( { name: normalizedName } );
						} }
					/>
					{ type !== 'radio' && (
						<ToggleControl
							checked={ isRequired }
							onChange={ ( newRequired ) =>
								props.setAttributes( {
									isRequired: newRequired,
								} )
							}
							label={ __( 'Required', 'cf7-blocks' ) }
							help={ __(
								'Marks the field as required.',
								'cf7-blocks'
							) }
						/>
					) }

					<ToggleControl
						checked={ isLabelFirst }
						onChange={ ( newLabelFirst ) =>
							props.setAttributes( {
								isLabelFirst: newLabelFirst,
							} )
						}
						label={ __(
							'Put a label first, a checkbox last',
							'cf7-blocks'
						) }
						help={ __(
							'Put a label first, a checkbox last.',
							'cf7-blocks'
						) }
					/>
				</PanelBody>
			</InspectorControls>
			<InspectorAdvancedControls>
				<TextControl
					value={ id }
					label={ __( 'Unique Id', 'cf7-blocks' ) }
					help={ __( 'Add a unique id attribute.', 'cf7-blocks' ) }
					onChange={ ( newId ) => {
						const idWithoutSpace = newId.replace( ' ', '' );
						props.setAttributes( { id: idWithoutSpace } );
					} }
				/>
			</InspectorAdvancedControls>
		</>
	);
}

export default Inspector;
