/**
 * WordPress Dependencies
 */
import { __, sprintf } from '@wordpress/i18n';
import { PanelBody, TextControl, ToggleControl } from '@wordpress/components';
import {
	InspectorControls,
	InspectorAdvancedControls,
} from '@wordpress/block-editor';

/**
 * Custom Dependencies
 */

import { convertSelectionBlockToCF7Shortcode } from '../utils/convert-to-cf7-shortcode';

function Inspector( props ) {
	const {
		id,
		type,
		name,
		showLabel,
		isRequired,
		isLabelFirst,
		isMultipleSelect,
		isFirstBlankItem,
		autogeneratedName,
	} = props.attributes;

	return (
		<>
			<InspectorControls>
				<PanelBody title={ __( 'Generated Shortcode', 'cf7-blocks' ) }>
					<TextControl
						style={ { maxWidth: '100%' } }
						value={ convertSelectionBlockToCF7Shortcode(
							props.attributes
						) }
					/>
				</PanelBody>
				<PanelBody title={ __( 'General', 'cf7-blocks' ) }>
					<TextControl
						value={ name }
						label={ __( 'Name', 'cf7-blocks' ) }
						placeholder={ autogeneratedName }
						help={ __(
							'Assign a unique field name',
							'cf7-blocks'
						) }
						onChange={ ( newName ) => {
							const normalizedName = newName
								.toLowerCase()
								.replace( ' ', '-' );

							props.setAttributes( { name: normalizedName } );
						} }
					/>
					{ type === 'select' && (
						<>
							<ToggleControl
								checked={ isMultipleSelect }
								onChange={ ( newIsMultipleSelect ) =>
									props.setAttributes( {
										isMultipleSelect: newIsMultipleSelect,
									} )
								}
								label={ __(
									'Multiple Selection',
									'cf7-blocks'
								) }
								help={ __(
									'Allow multiple selection.',
									'cf7-blocks'
								) }
							/>
							<ToggleControl
								checked={ isFirstBlankItem }
								onChange={ ( newIsFirstBlankItem ) =>
									props.setAttributes( {
										isFirstBlankItem: newIsFirstBlankItem,
									} )
								}
								label={ __( 'First blank item', 'cf7-blocks' ) }
								help={ __(
									'Insert a blank item as the first option.',
									'cf7-blocks'
								) }
							/>
						</>
					) }
					{ type !== 'radio' && (
						<ToggleControl
							checked={ isRequired }
							onChange={ ( newRequired ) =>
								props.setAttributes( {
									isRequired: newRequired,
								} )
							}
							label={ __( 'Required', 'cf7-blocks' ) }
							help={ __(
								'Marks the field as required.',
								'cf7-blocks'
							) }
						/>
					) }
					<ToggleControl
						checked={ showLabel }
						onChange={ ( newShowLabel ) =>
							props.setAttributes( {
								showLabel: newShowLabel,
							} )
						}
						label={ __( 'Label', 'cf7-blocks' ) }
						help={ __(
							'Displays an additional label above the field.',
							'cf7-blocks'
						) }
					/>

					<ToggleControl
						checked={ isLabelFirst }
						onChange={ ( newLabelFirst ) =>
							props.setAttributes( {
								isLabelFirst: newLabelFirst,
							} )
						}
						label={ __(
							'Put a label first, a checkbox last',
							'cf7-blocks'
						) }
						help={ __(
							'Put a label first, a checkbox last.',
							'cf7-blocks'
						) }
					/>
				</PanelBody>
			</InspectorControls>
			<InspectorAdvancedControls>
				<TextControl
					value={ id }
					label={ __( 'Unique Id', 'cf7-blocks' ) }
					help={ __( 'Add a unique id attribute.', 'cf7-blocks' ) }
					onChange={ ( newId ) => {
						const idWithoutSpace = newId.replace( ' ', '' );
						props.setAttributes( { id: idWithoutSpace } );
					} }
				/>
			</InspectorAdvancedControls>
		</>
	);
}

export default Inspector;
