/**
 * WordPress Dependencies
 */
import { sprintf } from '@wordpress/i18n';

/**
 * Generates a new field name based on the given type.
 *
 * @param {string} type - Field type.
 * @return {string} - Autogenerated field name.
 */
export default function generateFieldName( type ) {
	const uniqueId = Math.floor( Math.random() * 1000 );

	return sprintf( '%s-%d', type, uniqueId );
}
