name: Build development zip
on: push
jobs:
    build:
        name: Build development zip
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: [8.0]
                node-version: [16.x]
        steps:
            - name: Checkout code
              uses: actions/checkout@v1

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '${{ matrix.php }}'
                  tools: composer:v1

            - name: Build autoloader
              run: composer install --no-dev

            - name: Using Node version ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Installing lerna
              run: npm install lerna -g

            - name: bootstrap, npm install, build, and test
              run: |
                  npm install -f
                  npm run build
                  lerna clean -y
                  touch .devbuild
              env:
                  CI: true
                  INFURA_KEY: a2542fe40386473b9cce6550ebd9e871
            - name: Package
              uses: actions/upload-artifact@v2
              with:
                  name: cf7-blocks
                  retention-days: 1
                  path: |
                      ${{ github.workspace }}/
                      !${{ github.workspace }}/node_modules/
                      !${{ github.workspace }}/.github/
                      !${{ github.workspace }}/.git/
                      !${{ github.workspace }}/.editorconfig
                      !${{ github.workspace }}/.eslintrc.js
                      !${{ github.workspace }}/gruntfile.js
                      !${{ github.workspace }}/.husky
                      !${{ github.workspace }}/.eslintignore
                      !${{ github.workspace }}/.gitignore
                      !${{ github.workspace }}/.dev
                      !${{ github.workspace }}/.svgrrc
                      !${{ github.workspace }}/.prettierrc.js
                      !${{ github.workspace }}/.prettierignore
                      !${{ github.workspace }}/.phpcs.xml.dist
                      !${{ github.workspace }}/webpack.config.js
                      !${{ github.workspace }}/composer.json
                      !${{ github.workspace }}/composer.lock
                      !${{ github.workspace }}/package.json
                      !${{ github.workspace }}/package-lock.json
                      !${{ github.workspace }}/readme.md
                      !${{ github.workspace }}/lerna.json
                      !${{ github.workspace }}/cypress
